name: tf2

channels:
  - defaults
  - anaconda

dependencies:
  - python==3.11.9
  - pip
  - jupyter
  - chardet  # jupyter needs requests, which needs this.
  - pmdarima
  - prophet
  - plotly  # used by prophet for plotting
  - statsmodels
  - scikit-learn
  - pytest
  - graphviz
  - pip:
      - pipdeptree # or conda install -c conda-forge pipdeptree
      - matplotlib
      - seaborn
      - tensorflow
      - kaleido # plotly show png
      - pydot
      - visualkeras
      - pytorch